version: "3.7"
services:

  postgres:
    image: postgres
    expose:
      - 5432
    volumes:
      - metadata_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=FoolishPassword
      - POSTGRES_USER=druid
      - POSTGRES_DB=druid

  zookeeper:
    image: zookeeper
    ports:
      - "2181:2181"
    environment:
      - ZOO_MY_ID=1
      - ZOOKEEPER_CLIENT_PORT=2181

  coordinator:
    image: ghcr.io/arm64-compat/apache/druid:25.0.0
    volumes:
      - druid_shared:/opt/shared
      - coordinator_var:/opt/druid/var
    depends_on:
      - zookeeper
      - postgres
    ports:
      - "8081:8081"
    command:
      - coordinator
    env_file:
      - etc/druid/.env

  broker:
    image: ghcr.io/arm64-compat/apache/druid:25.0.0
    volumes:
      - broker_var:/opt/druid/var
    depends_on:
      - zookeeper
      - postgres
      - coordinator
    ports:
      - "8082:8082"
    command:
      - broker
    env_file:
      - etc/druid/.env

  historical:
    image: ghcr.io/arm64-compat/apache/druid:25.0.0
    volumes:
      - druid_shared:/opt/shared
      - historical_var:/opt/druid/var
    depends_on: 
      - zookeeper
      - postgres
      - coordinator
    ports:
      - "8083:8083"
    command:
      - historical
    env_file:
      - ./etc/druid/.env

  middlemanager:
    image: ghcr.io/arm64-compat/apache/druid:25.0.0
    volumes:
      - druid_shared:/opt/shared
      - middle_var:/opt/druid/var
    depends_on: 
      - zookeeper
      - postgres
      - coordinator
    ports:
      - "8091:8091"
      - "8100-8105:8100-8105"
    command:
      - middleManager
    env_file:
      - etc/druid/.env

  router:
    image: ghcr.io/arm64-compat/apache/druid:25.0.0
    volumes:
      - router_var:/opt/druid/var
    depends_on:
      - zookeeper
      - postgres
      - coordinator
    ports:
      - "8888:8888"
    command:
      - router
    env_file:
      - etc/druid/.env

  superset-db:
    image: postgres
    expose:
      - 5432
    environment:
      - POSTGRES_USER=superset
      - POSTGRES_PASSWORD=superset
      - POSTGRES_DB=superset
    volumes:
      - superset_data:/var/lib/postgresql/data

  superset:
    image: apache/superset:latest
    platform: linux/amd64
    environment:
      - SUPERSET_SECRET_KEY=superset
      - DATABASE_DB=superset
      - DATABASE_HOST=superset-db
      - DATABASE_PASSWORD=superset
      - DATABASE_USER=superset
      - DATABASE_PORT=5432
      - DATABASE_DIALECT=postgresql
    ports:
      - 8088:8088
    depends_on:
      - superset-db
    volumes:
      - superset_home:/app/superset_home

volumes:
  metadata_data: {}
  middle_var: {}
  historical_var: {}
  broker_var: {}
  coordinator_var: {}
  router_var: {}
  druid_shared: {}
  superset_data: {}
  superset_home: {}
